# Урок 2

## Матрицы и матричные операции. Часть 1

__Матрицей__ размера $m\times n$ называется прямоугольная таблица, состоящая из $m$ строк и $n$ столбцов. Элементы матрицы, обозначаемой заглавной буквой (например, $A$), обычно обозначаются $a_{ij}$, где индексы $i$ и $j$ — номера строки и столбцы, в которых находится элемент. 

$$\begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\ 
a_{21} & a_{22} & \cdots & a_{2n}\\  
\cdots & \cdots & \cdots & \cdots \\ 
a_{m1} & a_{m2} & \cdots & a_{mn}\\ 
\end{pmatrix}$$

Числа $m$ и $n$ называются _порядками_ матрицы. Если $m=n$, то матрица называется _квадратной_, а число $m=n$ — её _порядком_.

Для краткого обозначения матрицы иногда используется символ $\left\|a_{ij}\right\|$ или выражение $A = \left\|a_{ij}\right\| = (a_{ij}) ~ (i = 1,2...,m; ~ j = 1,2...,n).$

В машинном обучении матрицы обычно используются для хранения информации об объектах и их признаках. Обычно по строкам располагаются объекты, а по столбцам — признаки, то есть некоторые свойства объектов, значения которых используются для обучения модели, и которые затем эта модель предсказывает для других объектов.

Векторы, изученные в предыдущих уроках, считаются частными случаями матриц: в частности, упомянутая в предыдущем уроке _вектор-строка_ (матрица размера $1\times m$) и _вектор-столбец_ (матрица размера $n\times1$):

$$\begin{pmatrix}
1 & 2 & 3
\end{pmatrix} ~ и ~ \begin{pmatrix}
1\\ 
2\\ 
3
\end{pmatrix}.$$

В Python работа с матрицами обычно ведётся посредством библиотеки NumPy.

In [ ]:
import numpy as np

Самый простой способ создать матрицу — применение функции `numpy.array(list, dtype=None ...)`. Здесь `list` — список итерируемых объектов, которые составят строки матрицы. Мы уже использовали эту функцию в первом уроке для создания векторов — частный одномерный случай матриц.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Матричные операции

### 1. Сложение матриц

Рассмотрим матрицу $A$ размера $m\times n$, состоящую из элементов $a_{ij}$, и $B$ того же размера, в которую входят элементы $b_{ij}$.

Складывать можно только __матрицы одинаковых порядков__, и сложение их происходит поэлементно, то есть _суммой_ двух матриц $A+B$ будет матрица $C$ того же размера, состоящая из элементов $c_{ij}=a_{ij}+b_{ij}$:

$$A + B = 
\begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\ 
a_{21} & a_{22} & \cdots & a_{2n}\\  
\cdots & \cdots & \cdots & \cdots \\ 
a_{m1} & a_{m2} & \cdots & a_{mn}\\ 
\end{pmatrix} + \begin{pmatrix}
b_{11} & b_{12} & \cdots & b_{1n}\\ 
b_{21} & b_{22} & \cdots & b_{2n}\\  
\cdots & \cdots & \cdots & \cdots \\ 
b_{m1} & b_{m2} & \cdots & b_{mn}\\ 
\end{pmatrix} = \begin{pmatrix}
a_{11} + b_{11} & a_{12} + b_{12} & \cdots & a_{1n} + b_{1n}\\ 
a_{21} + b_{21}& a_{22} + b_{22}& \cdots & a_{2n} + b_{2n}\\  
\cdots & \cdots & \cdots & \cdots \\ 
a_{m1} + b_{m1} & a_{m2} + b_{m2} & \cdots & a_{mn} + b_{mn}\\ 
\end{pmatrix}
= C.$$

__Пример__

Сложим две матрицы, заполненные натуральными числами:

$$\begin{pmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{pmatrix} + \begin{pmatrix}
1 & 1 & 1\\ 
1 & 1 & 1\\ 
1 & 1 & 1
\end{pmatrix} = \begin{pmatrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{pmatrix}.$$


И проведём ту же операцию через Python:

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.ones((3,3))  # функция для создания матрицы размера (x,y), заполненной единицами

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица С = A + B\n{a + b}')

Матрица A
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Матрица B
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Матрица С = A + B
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


Операция сложения матриц обладает теми же свойствами, что и операция сложения вещественных чисел, а именно:<br>
1) переместительным свойством: $A+B=B+A;$<br>
2) сочетательным свойством: $(A+B)+C=A+(B+C).$

### 2. Умножение матриц на число

Умножение матрицы на число происходит так же просто, как и сложение: _произведением матрицы_ $A=\left\|a_{ij}\right\|$ на число $\lambda$ считается матрица $C = \left\|c_{ij}\right\|$, элементы которой $c_{ij}=\lambda a_{ij}$, то есть каждый элемент матрицы умножается на число $\lambda$:

$$\lambda\cdot\begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\ 
a_{21} & a_{22} & \cdots & a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
a_{m1} & a_{m2} & \cdots & a_{mn}\\ 
\end{pmatrix}=
\begin{pmatrix}
\lambda a_{11} & \lambda a_{12} & \cdots & \lambda a_{1n}\\ 
\lambda a_{21} & \lambda a_{22} & \cdots & \lambda a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
\lambda a_{m1} & \lambda a_{m2} & \cdots & \lambda a_{mn}\\ 
\end{pmatrix}.$$

__Пример__

$$3\cdot\begin{pmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{pmatrix} = \begin{pmatrix}
3 & 6 & 9\\ 
12 & 15 & 18\\ 
21 & 24 & 27
\end{pmatrix}.$$


Это происходит и в Python:

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
k = 3

print(f'Матрица А\n{a}\n')
print(f'Матрица 3*А\n{k*a}')

Матрица А
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Матрица 3*А
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


Умножение матрицы на число обладает следующими свойствами:<br>
1. $(\lambda \mu)A=\lambda(\mu A).$<br>
2. $\lambda (A+B)=\lambda A + \lambda B.$<br>
3. $(\lambda + \mu) A = \lambda A + \mu A.$

### 3. Перемножение матриц

_Произведением_ матрицы $A = \left\|a_{ij}\right\|$, имеющей порядки $m$ и $n$, и матрицы $B = \left\|b_{ij}\right\|$, включающей порядки $n$ и $k$, называется матрица $C = \left\|c_{ij}\right\|$ с порядками $m$ и $k$:

$$C = \begin{pmatrix}
c_{11} & c_{12} & \cdots & c_{1k}\\ 
c_{21} & c_{22} & \cdots & c_{2k}\\ 
\cdots & \cdots & \ddots & \cdots\\ 
c_{m1} & c_{m2} & \cdots & c_{mk}
\end{pmatrix},$$

наполненная элементами, определяемыми формулой:

$$ c_{ij}=\sum_{p=1}^{n}a_{ip}b_{pj}.$$

Правило перемножения матриц формулируется словесно следующим образом: _элемент $c_{ij}$, стоящий на пересечении $i$-й строки и $j$-го столбца матрицы $C=A\cdot B$, равен сумме попарных произведений соответствующих элементов $i$-й строки матрицы $A$ и $j$-го столбца матрицы $B$._

Матрицу $A$ можно умножить не на любую матрицу $B$: __важно, чтобы число столбцов матрицы $A$ было равно числу строк матрицы $B$.__

В частности, определить оба произведения $A\cdot B$ и $B\cdot A$ можно только тогда, когда число столбцов $A$ совпадает с числом строк $B$, а число строк $A$ — с числом столбцов $B$. В этом случае матрицы $A\cdot B$ и $B\cdot A$ будут квадратными. Их порядок в общем случае будет различным и совпадать только при квадратных матрицах $A$ и $B$.

__Пример 1__

Скалярное произведение векторов, рассмотренное нами на предыдущем уроке, можно понимать как умножение вектор-строки на вектор-столбец.

__Пример 2__

Для лучшего понимания рассмотрим в качестве примера перемножение квадратных матриц второго порядка:

$$\begin{pmatrix}
a_{11} & a_{12}\\ 
a_{21} & a_{22}
\end{pmatrix} \begin{pmatrix}
b_{11} & b_{12}\\ 
b_{21} & b_{22}
\end{pmatrix}=\begin{pmatrix}
(a_{11}b_{11} + a_{12}b_{21}) & (a_{11}b_{12} + a_{12}b_{22})\\ 
(a_{21}b_{11} + a_{22}b_{21}) & (a_{21}b_{12} + a_{22}b_{22})
\end{pmatrix}.$$

__Пример 3__

Перемножим матрицы:

$$A=\begin{pmatrix}
1 & 0\\ 
2 & 1\\ 
10 & 5
\end{pmatrix} \; и \; B=\begin{pmatrix}
2 & 0 & 0\\ 
0 & 0 & 1
\end{pmatrix}.$$

$$A\cdot B=\begin{pmatrix}
1\cdot2+0\cdot0 & 1\cdot0+2\cdot0 & 1\cdot0+0\cdot1\\ 
2\cdot2+1\cdot0 & 2\cdot0+1\cdot0 & 2\cdot0+1\cdot1\\ 
10\cdot2+5\cdot0 & 10\cdot0+5\cdot0 & 10\cdot0+5\cdot1
\end{pmatrix}=\begin{pmatrix}
2 & 0 & 0\\ 
4 & 0 & 1\\ 
20 & 0 & 5
\end{pmatrix}.$$

Сделаем то же самое через Python.

В библиотеке NumPy перемножение матриц осуществляется посредством тех же инструментов, которые мы использовали для нахождения скалярного произведения векторов — функции `numpy.dot(a, b)` или метода `a.dot(b)`. Только в этом случае `a` и `b` — матрицы.

In [ ]:
A = np.array([[1, 0], [2, 1], [10, 5]])
B = np.array([[2, 0, 0], [0, 0, 1]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[ 1  0]
 [ 2  1]
 [10  5]]
Матрица B
[[2 0 0]
 [0 0 1]]
Матрица AB
[[ 2  0  0]
 [ 4  0  1]
 [20  0  5]]


Перемножим матрицы, не отвечающие правилу соответствия количества строк и столбцов:

In [ ]:
A = np.array([[1, 0], [2, 1], [10, 5]])
B = np.array([[2, 0, 0], [0, 0, 1], [0, 0, 1]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[ 1  0]
 [ 2  1]
 [10  5]]
Матрица B
[[2 0 0]
 [0 0 1]
 [0 0 1]]


ValueError: ignored

Запуск кода в ячейке выше приводит к ошибке, так как количество столбцов первой матрицы не равно количеству строк второй при перемножении.

__Пример 4__

Перемножим матрицы:

$$A = \begin{pmatrix}
1 & 3\\ 
2 & 6
\end{pmatrix} ~ 
и ~
B = \begin{pmatrix}
9 & 6\\ 
-3 & -2
\end{pmatrix}.$$

$$\begin{pmatrix}
1 & 3\\ 
2 & 6
\end{pmatrix} \cdot
\begin{pmatrix}
9 & 6\\ 
-3 & -2
\end{pmatrix} = 
\begin{pmatrix}
1\cdot 9 + 3\cdot (-3) & 1\cdot6 + 3\cdot (-2)\\ 
2\cdot 9 + 6\cdot (-3) & 2\cdot6 + 6\cdot (-2)
\end{pmatrix} = 
\begin{pmatrix}
0 & 0\\ 
0 & 0
\end{pmatrix}.
$$

Это важный пример, показывающий наличие среди матриц делителей нуля, то есть ненулевых матриц, при перемножении дающих _нулевую матрицу_.

Из специфики произведения матриц следует, что оно не обладает свойством коммутативности, то есть $AB\neq BA$. В общем случае это справедливо даже для квадратных матриц, например:

$$\begin{pmatrix}
0 & 0\\ 
0 & 1
\end{pmatrix} \begin{pmatrix}
0 & 0\\ 
1 & 0
\end{pmatrix}=\begin{pmatrix}
0 & 0\\ 
1 & 0
\end{pmatrix},$$
$$\begin{pmatrix}
0 & 0\\ 
1 & 0
\end{pmatrix}\begin{pmatrix}
0 & 0\\ 
0 & 1
\end{pmatrix}=\begin{pmatrix}
0 & 0\\ 
0 & 0
\end{pmatrix}.$$


Однако произведению матриц __подходящих размеров__ свойственны другие особенности:

1. Ассоциативность: $(AB)C = A(BC).$

   __Доказательство__

    Возьмём матрицы $A$ размера $m\times n$, $B$ размера $n\times k$, $C$ размера $k\times l$. Тогда, по определению $i,j$-й элемент произведения матрицы $AB$ на матрицу $C$ равен:

$$\{(AB)C\}_{ij}=\sum_{p=1}^{k}\{AB\}_{ip}c_{pj}=\sum_{p=1}^{k}\  
(\sum_{q=1}^{n}a_{iq}b_{qp})c_{pj}=\sum_{q=1}^{n}a_{iq}(\sum_{p=1}^{k}b_{qp}c_{pj})=\{A(BC)\}_{ij},
$$

что и требовалось доказать.


2. Дистрибутивность: $(A+B)C = AC + BC$ и $A(B+C) = AB + AC$.

    Это свойство вытекает из определений суммы и произведения матриц.

__Возведение матриц в степень__ считается частным случаем перемножения:

$$A\cdot A = A^{2}.$$

__Пример__

$$\begin{pmatrix}
1 & 1\\ 
0 & 1
\end{pmatrix}^{2} = 
\begin{pmatrix}
1 & 1\\ 
0 & 1
\end{pmatrix} \cdot
\begin{pmatrix}
1 & 1\\ 
0 & 1
\end{pmatrix} = 
\begin{pmatrix}
1\cdot1 + 1\cdot0 & 1\cdot1 + 1\cdot1\\ 
0\cdot1 + 1\cdot0 & 0\cdot1 + 1\cdot1
\end{pmatrix} = 
\begin{pmatrix}
1 & 2\\ 
0 & 1
\end{pmatrix}
$$

### 4. Транспонирование матриц

Рассмотрим ещё одну распространённую процедуру при работе с матрицами, называемую _транспонированием._

Пусть есть матрица $A$ размера $m\times n$. В таком случае матрица $B$, полученная транспонированием матрицы $A$ и обозначаемая $B=A^{T}$, будет представлять собой матрицу размера $n\times m$, элементы которой $b_{ij}=a_{ji}$. Иными словами, транспонированная матрица — это матрица, отражённая относительно главной диагонали, на которой располагаются элементы с $i=j$. При транспонировании строки исходной матрицы становятся столбцами, а столбцы — строками.

__Пример__

$$A=\begin{pmatrix}
8 & 5 & 3\\ 
4 & 6 & 1\\ 
0 & 11 & 9\\ 
2 & 7 & 10
\end{pmatrix}, \;A^{T}=\begin{pmatrix}
8 & 4 & 0 & 2\\ 
5 & 6 & 11 & 7\\ 
3 & 1 & 9 & 10
\end{pmatrix}.$$

В NumPy транспонированная матрица вычисляется по функции `numpy.transpose(array)` или по методу `array.T`, где `array` — матрица.

In [ ]:
a = np.array([[8, 5, 3], [4, 6, 1], [0, 11, 9], [2, 7, 10]])

print(f'Матрица:\n{a}')
print(f'Транспонированная матрица:\n{a.T}')

Матрица:
[[ 8  5  3]
 [ 4  6  1]
 [ 0 11  9]
 [ 2  7 10]]
Транспонированная матрица:
[[ 8  4  0  2]
 [ 5  6 11  7]
 [ 3  1  9 10]]


Некоторые важные свойства транспонирования:<br>
1. $(A+B)^{T}=A^{T}+B^{T}.$<br>
2. $(A\cdot B)^{T}=B^{T}\cdot A^{T}.$

## Типы матриц

Рассмотрим некоторые особые типы матриц, которые понадобятся нам в будущем, в частности, при рассмотрении темы линейных преобразований и матричных разложений.

### Диагональная матрица

_Диагональная матрица_ — матрица, в которой все элементы, не лежащие на главной диагонали, нулевые:

$$D = \begin{pmatrix}
d_{1} & 0 & \cdots & 0\\ 
0 & d_{2} & \cdots  & 0\\ 
\cdots & \cdots & \ddots & \cdots\\ 
0 & 0 & \cdots & d_{n}
\end{pmatrix}.$$

Частным случаем диагональной матрицы считается _единичная матрица_, обычно обозначаемая $E$ или $I$ — это матрица, в которой главную диагональ занимают единицы, а остальные элементы — нулевые:

$$E=\begin{pmatrix}
1 & 0 & \cdots & 0\\ 
0 & 1 & \cdots  & 0\\ 
\cdots & \cdots & \ddots & \cdots\\ 
0 & 0 & \cdots & 1
\end{pmatrix}.$$


В NumPy единичная матрица задаётся по функции `numpy.eye(n)`, где `n` — порядок матрицы:

In [ ]:
e = np.eye(5)
print(f'Единичная матрица:\n{e}')

Единичная матрица:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Треугольная матрица

_Треугольная матрица_ — квадратная матрица, у которой все элементы, стоящие ниже или выше главной диагонали, нулевые.

Треугольная матрица, у которой все элементы ниже главной диагонали равны нулю, называется _верхней треугольной (верхне-треугольной)_ матрицей:

$$\begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\ 
0 & a_{22} & \cdots & a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
0 & 0 & \cdots & a_{nn}\\ 
\end{pmatrix}.$$

Треугольная матрица, у которой все элементы выше главной диагонали равны нулю, называется _нижней треугольной (нижне-треугольной)_ матрицей:

$$\begin{pmatrix}
a_{11} & 0 & \cdots & 0\\ 
a_{21} & a_{22} & \cdots & 0\\  
\cdots & \cdots & \ddots & \cdots \\ 
a_{n1} & a_{n2} & \cdots & a_{nn}\\ 
\end{pmatrix}.$$

Важное свойство верхне-треугольных матриц: _при перемножении верхне-треугольных матриц свойство верхней треугольности сохраняется._

__Пример__

In [ ]:
import numpy as np
a = np.array([[4, 5, 2], [1, -2, 3]])
b = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица AB\n{np.dot(a, b)}')

Матрица A
[[ 4  5  2]
 [ 1 -2  3]]

Матрица B
[[ 4  1]
 [ 5 -2]
 [ 2  3]]

Матрица AB
[[45  0]
 [ 0 14]]


### Ортогональная матрица

Матрица $A$ называется _ортогональной_, если:

$$AA^{T}=A^{T}A=E.$$

__Пример__

Ортогональной считается матрица:

$$\begin{pmatrix}
cos\varphi & -sin\varphi\\ 
sin \varphi & cos\varphi
\end{pmatrix}.$$

Убедимся, что это действительно так:

$$\begin{pmatrix}
cos\varphi & -sin\varphi\\ 
sin \varphi & cos\varphi
\end{pmatrix} \cdot 
\begin{pmatrix}
cos\varphi & sin\varphi\\ 
-sin \varphi & cos\varphi
\end{pmatrix} = 
\begin{pmatrix}
cos\varphi \cdot cos\varphi + (-sin\varphi) \cdot (-sin\varphi) & cos\varphi \cdot sin\varphi + (-sin\varphi) \cdot cos\varphi\\ 
sin\varphi \cdot cos\varphi + cos\varphi \cdot (-sin\varphi) & sin\varphi \cdot sin\varphi + cos\varphi \cdot cos\varphi
\end{pmatrix} = 
\begin{pmatrix}
1 & 0\\ 
0 & 1
\end{pmatrix}.$$

### Симметричная матрица

Матрица $A$ называется _симметричной_, если:

$$A=A^{T},$$

то есть симметричная матрица симметрична относительно главной диагонали.

## Практическое задание

Все задания рекомендуется делать вручную, проверяя полученные результаты через NumPy.

__1.__ Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    
__2.__ Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.

__5*.__ Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

# Матрицы и матричные операции. Часть 2

## Определитель матрицы

Рассмотрим произвольную квадратную матрицу порядка $n$:

$$A=\begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\ 
a_{21} & a_{22} & \cdots & a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
a_{n1} & a_{n2} & \cdots & a_{nn}\\ 
\end{pmatrix}.$$


С каждой такой матрицей свяжем численную характеристику, называемую _определителем_, соответствующим этой матрице. 


Сразу отметим, что понятие определителя имеет смысл __только для квадратных матриц__.

Если порядок $n$ матрицы равен единице, то есть эта матрица состоит из одного элемента $a_{11}$, определителем, соответствующим такой матрице, назовём сам этот элемент.

Если порядок матрицы равен $2$, то есть матрица имеет вид:

$$A=\begin{pmatrix}
a_{11} & a_{12}\\ 
a_{21} & a_{22}
\end{pmatrix},$$

то определителем второго порядка, соответствующим такой матрице, назовём число, равное:

$$a_{11}a_{22} - a_{12}a_{21}.$$

Словесно это правило можно сформулировать так: _определитель второго порядка, соответствующий матрице $A$, равен разности произведения элементов, стоящих на главной диагонали этой матрицы, и элементов, располагающихся на её побочной диагонали._

Определитель матрицы $A$ обозначается как $detA$, или $|A|$, то есть определитель второго порядка можно записать как:

$$detA=|A|=\begin{vmatrix}
a_{11} & a_{12}\\ 
a_{21} & a_{22}
\end{vmatrix}=a_{11}a_{22} - a_{12}a_{21}.$$

Будем двигаться дальше и выясним понятие определителя для матриц порядка $n\geq2.$

Для этого введём понятие минора. _Минором_ любого элемента $a_{ij}$ матрицы $n$-го порядка назовём определитель порядка $n-1$, соответствующий матрице, которая получается из исходной матрицы путём вычёркивания $i$-й строки и $j$-го столбца. Это строка и столбец, на пересечении которых стоит элемент $a_{ij}$). Обозначать минор будем символом $M_{ij}$.

Определителем матрицы порядка $n$ назовём число, равное:

$$detA=\begin{vmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\ 
a_{21} & a_{22} & \cdots & a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
a_{n1} & a_{n2} & \cdots & a_{nn}\\ 
\end{vmatrix} = 
\sum_{j=1}^{n}(-1)^{j+1}a_{1j}M_{1j}.$$

Эта формула представляет собой правило составления определителя порядка $n$ по элементам первой строки и минорам $M_{1j}$, служащим определителями порядка $n-1$.

Заметим, что при $n=2$ правило совпадает с введённым ранее правилом получения определителя для матриц второго порядка: в этом случае миноры элементов первой строки имеют вид $M_{11}=a_{22}$, $M_{12}=a_{21}$.

__Теорема__

При любом произвольном номере строки $i~(i=1,2...,n)$ для определителя порядка $n$ справедлива формула:

$$detA = \sum_{j=1}^{n}(-1)^{i+j}a_{ij}M_{ij},$$

называемая _разложением этого определителя по $i$-й строке._

__Теорема__

При любом произвольном номере столбца $j~(j=1,2...,n)$ для определителя порядка $n$ справедлива формула:

$$detA = \sum_{i=1}^{n}(-1)^{i+j}a_{ij}M_{ij},$$

называемая _разложением этого определителя по $j$-му столбцу._

Таким образом, определитель может сформироваться разложением как по произвольной строке исходной матрицы, так и по произвольному её столбцу.

__Пример__

Вычислим определитель:

$$\begin{vmatrix}
1 & 2 & 1\\ 
1 & 1 & 4\\ 
2 & 3 & 6
\end{vmatrix}.$$

__Решение__

$$\begin{vmatrix}
1 & 2 & 1\\ 
1 & 1 & 4\\ 
2 & 3 & 6
\end{vmatrix}=
1\cdot\begin{vmatrix}
1 & 4\\ 
3 & 6
\end{vmatrix}-
2\cdot\begin{vmatrix}
1 & 4\\ 
2 & 6
\end{vmatrix}+
1\cdot\begin{vmatrix}
1 & 1\\ 
2 & 3
\end{vmatrix}=1\cdot(1\cdot6-3\cdot4)-2\cdot(1\cdot6-2\cdot4)+1\cdot(1\cdot3-2\cdot1)= \\
=-6+4+1=-1.
$$

__Пример__

Найдём определитель матрицы:

$$A=\begin{pmatrix}
-1 & -4 & 0 & -2 \\ 
0 & 1 & 5 & 4 \\  
3 & 1 & 1 & 0 \\ 
-1 & 0 & 2 & 2\\ 
\end{pmatrix},$$

разложив его<br>
* по элементам 2-го столбца;<br>
* по элементам 3-й строки.

__Решение__

1. Разложение определителя 4-го порядка по элементам 2-го столбца будет иметь вид:

$$\begin{vmatrix}
a_{11} & a_{12} & a_{13} & a_{14}\\ 
a_{21} & a_{22} & a_{23} & a_{24}\\  
a_{31} & a_{32} & a_{33} & a_{34} \\ 
a_{41} & a_{42} & a_{43} & a_{44}\\ 
\end{vmatrix} = 
(-1)^{1+2}a_{12}\begin{vmatrix}
a_{21} & a_{23} & a_{24}\\  
a_{31} & a_{33} & a_{34} \\ 
a_{41} & a_{43} & a_{44}\\ 
\end{vmatrix} + (-1)^{2+2}a_{22}\begin{vmatrix}
a_{11} & a_{13} & a_{14}\\  
a_{31} & a_{33} & a_{34} \\ 
a_{41} & a_{43} & a_{44}\\ 
\end{vmatrix} + (-1)^{3+2}a_{32}\begin{vmatrix}
a_{11} & a_{13} & a_{14}\\ 
a_{21} & a_{23} & a_{24}\\  
a_{41} & a_{43} & a_{44}\\ 
\end{vmatrix} + (-1)^{4+2}a_{42}\begin{vmatrix}
a_{11} & a_{13} & a_{14}\\ 
a_{21} & a_{23} & a_{24}\\  
a_{31} & a_{33} & a_{34} \\ 
\end{vmatrix}.$$

Таким образом, для матрицы $A$:

$$\begin{vmatrix}
-1 & -4 & 0 & -2 \\ 
0 & 1 & 5 & 4 \\  
3 & 1 & 1 & 0 \\ 
-1 & 0 & 2 & 2\\ 
\end{vmatrix} = 4\begin{vmatrix}
0 & 5 & 4 \\ 
3 & 1 & 0\\  
-1 & 2 & 2 \\ 
\end{vmatrix} + \begin{vmatrix}
-1 & 0 & -2\\ 
3 & 1 & 0\\  
-1 & 2 & 2 \\ 
\end{vmatrix} - \begin{vmatrix}
-1 & 0 & -2\\ 
0 & 5 & 4\\  
-1 & 2 & 2 \\ 
\end{vmatrix} + 0.$$

Так задача нахождения определителя 4-го порядка сводится к нахождению трёх определителей 3-го порядка. Вычислим первый, разложив по первой строке:

$$\begin{vmatrix}
0 & 5 & 4 \\ 
3 & 1 & 0\\  
-1 & 2 & 2 \\ 
\end{vmatrix} = 
0\begin{vmatrix}
1 & 0\\  
2 & 2 \\ 
\end{vmatrix}
-5\begin{vmatrix}
3 & 0\\  
-1 & 2 \\ 
\end{vmatrix} + 
4\begin{vmatrix}
3 & 1\\  
-1 & 2\\ 
\end{vmatrix} = 0\cdot(1\cdot2-2\cdot0)
-5\cdot(3\cdot2 - (-1)\cdot 0) + 4\cdot(3\cdot2 - (-1)\cdot1) = -2.$$

Аналогично вычисляем:
$$\begin{vmatrix}
-1 & 0 & -2\\ 
3 & 1 & 0\\  
-1 & 2 & 2 \\ 
\end{vmatrix} = 
(-1)\begin{vmatrix}
1 & 0\\  
2 & 2 \\ 
\end{vmatrix} - 
0\begin{vmatrix}
3 & 0\\  
-1 & 2 \\ 
\end{vmatrix} + 
(-2)\begin{vmatrix}
3 & 1\\  
-1 & 2 \\ 
\end{vmatrix} = 
(-1)\cdot(1\cdot2-2\cdot0) - 0\cdot(3\cdot2-(-1)\cdot0) + (-2)\cdot(3\cdot2-(-1)\cdot1) = -16,$$

$$\begin{vmatrix}
-1 & 0 & -2\\ 
0 & 5 & 4\\  
-1 & 2 & 2 \\ 
\end{vmatrix} = 
(-1)\begin{vmatrix}
5 & 4\\  
2 & 2 \\ 
\end{vmatrix} - 
0\begin{vmatrix}
0 & 4\\  
-1 & 2 \\ 
\end{vmatrix} +
(-2)\begin{vmatrix}
0 & 5\\  
-1 & 2\\ 
\end{vmatrix} = 
(-1)\cdot(5\cdot2 - 2\cdot4) - 0\cdot(0\cdot2-(-1)\cdot4) + (-2)\cdot(0\cdot2-(-1)\cdot5) = -12.$$

Подставляя полученные значения определителей в исходное разложение, получим:

$$|A| = 4\cdot(-2) + (-16) - (-12) = -12.$$

2. Разложение определителя 4-го порядка по элементам 3-й строки будет иметь вид:

$$\begin{vmatrix}
a_{11} & a_{12} & a_{13} & a_{14}\\ 
a_{21} & a_{22} & a_{23} & a_{24}\\  
a_{31} & a_{32} & a_{33} & a_{34} \\ 
a_{41} & a_{42} & a_{43} & a_{44}\\ 
\end{vmatrix} =
(-1)^{3+1}a_{31}\begin{vmatrix}
a_{12} & a_{13} & a_{14}\\ 
a_{22} & a_{23} & a_{24}\\  
a_{42} & a_{43} & a_{44}\\ 
\end{vmatrix} + 
(-1)^{3+2}a_{32}\begin{vmatrix}
a_{11} & a_{13} & a_{14}\\ 
a_{21} & a_{23} & a_{24}\\  
a_{41} & a_{43} & a_{44}\\ 
\end{vmatrix} + 
(-1)^{3+3}a_{33}\begin{vmatrix}
a_{11} & a_{12} & a_{14}\\ 
a_{21} & a_{22} & a_{24}\\  
a_{41} & a_{42} & a_{44}\\ 
\end{vmatrix} +
(-1)^{3+4}a_{34}\begin{vmatrix}
a_{11} & a_{12} & a_{13}\\ 
a_{21} & a_{22} & a_{23}\\  
a_{41} & a_{42} & a_{43}
\end{vmatrix}.$$

Для матрицы $A$:

$$\begin{vmatrix}
-1 & -4 & 0 & -2 \\ 
0 & 1 & 5 & 4 \\  
3 & 1 & 1 & 0 \\ 
-1 & 0 & 2 & 2\\ 
\end{vmatrix} = 3\begin{vmatrix}
-4 & 0 & -2 \\ 
1 & 5 & 4 \\  
0 & 2 & 2\\ 
\end{vmatrix} -\begin{vmatrix}
-1 & 0 & -2 \\ 
0 & 5 & 4 \\  
-1 & 2 & 2\\ 
\end{vmatrix} + \begin{vmatrix}
-1 & -4 & -2 \\ 
0 & 1 & 4 \\  
-1 & 0 & 2\\ 
\end{vmatrix} - 0.$$

Найдём определители третьего порядка:

$$\begin{vmatrix}
-4 & 0 & -2 \\ 
1 & 5 & 4 \\  
0 & 2 & 2\\ 
\end{vmatrix} = (-4)\cdot(5\cdot2-2\cdot4) - 0\cdot(1\cdot2 - 0\cdot4) + (-2)\cdot(1\cdot2-0\cdot5)= -12,$$

$$\begin{vmatrix}
-1 & 0 & -2 \\ 
0 & 5 & 4 \\  
-1 & 2 & 2\\ 
\end{vmatrix} = (-1)\cdot(5\cdot2-2\cdot4) - 0\cdot(0\cdot2-(-1)\cdot4) + (-2)\cdot(0\cdot2-(-1)\cdot5)= -12,$$

$$\begin{vmatrix}
-1 & -4 & -2 \\ 
0 & 1 & 4 \\  
-1 & 0 & 2\\ 
\end{vmatrix} = (-1)\cdot(1\cdot2-0\cdot4) - (-4)\cdot(0\cdot2-(-1)\cdot4) + (-2)\cdot(0\cdot0-(-1)\cdot1) = 12.$$

Подставляя полученные значения определителей в исходное разложение, получим:

$$|A| = 3\cdot(-12) - (-12) + 12 = -12.$$

### Выражение определителя напрямую через его элементы

Установим формулу нахождения детерминанта $n$-го порядка прямо через его элементы, минуя миноры.

Для этого введём понятия перестановок и транспозиций на множестве.

_Перестановкой_ на множестве $S=\{1,2,3...,n\}$ называется множество тех же чисел, упорядоченное некоторым образом:

$$\{1,2,3,4\}\Rightarrow\{3,4,1,2\}.$$

_Транспозицией_ называется такая перестановка, в которой переставлены местами только два элемента множества, в то время как остальные элементы остаются на своих местах:

$$\{1,2,3,4\}\Rightarrow\{\underline{4},2,3,\underline{1}\}.$$


Любую перестановку можно реализовать путём нескольких последовательных транспозиций. Например, перестановка $\{3,4,1,2\}$ представляет собой последовательность трёх транспозиций:

$$\{\underline{1},2,\underline{3},4\}\Rightarrow\{3,\underline{2},1,\underline{4}\}\Rightarrow\{3,4,1,2\}.$$

Принято, что перестановка содержит __инверсию__ элементов $i_{j}$ и $i_{k}$, если $i_{j}>i_{k}$ при $j<k.$

Например, наша перестановка $\{3,4,1,2\}$ содержит четыре инверсии: 

- $3$ и $1$, так как число $3$ стоит слева от меньшего числа $1$, и по аналогии — следующие;
- $3$ и $2$; 
- $4$ и $1$;
- $4$ и $2$.

Число инверсий определяет __чётность__ перестановки. То есть перестановка считается чётной, если она содержит чётное число инверсий, и нечётной, если нечётное.

_Для множества $S=\{1,2,3...,n\}$ существует $n!$ различных перестановок._

__Пример__

Возьмём множество $\{1,2,3\}$. Оно будет содержать $3!=6$ перестановок:

$$\{1,2,3\}, \{2,1,3\}, \{2,3,1\}, \{3,2,1\}, \{3,1,2\}, \{1,3,2\}.$$

При этом:

- перестановки $\{1,2,3\}$, $\{2,3,1\}$ и $\{3,1,2\}$ будут чётными;
- перестановки $\{2,1,3\}$, $\{3,2,1\}$ и $\{1,3,2\}$ будут нечётными.

__Вернёмся к понятию определителя__

Возьмём квадратную матрицу $A$ $n$-го порядка (размера $n\times n$) и множество $\{k_{1}, k_{2} ...,k_{n}\}$, которое представляет собой некоторую перестановку упорядоченного множества натуральных чисел $\{1,2...,n\}$.

Рассмотрим произведение, содержащее $n$ матричных элементов, взятых по одному из каждой строки, составленное следующим образом:

$$a_{1k_{1}}a_{2k_{2}}...a_{nk_{n}}.$$



Первый множитель — элемент из первой строки и $k_{1}$ столбца, второй — из второй строки и $k_{2}$ столбца и т. д. 

Вспомним, что существует $n!$ различных перестановок $\{k_{1}, k_{2} ...,k_{n}\}$ из индексов столбцов. Каждая из них будет формировать произведение указанного вида. Припишем каждому такому произведению знак $«+»$, если перестановка $\{k_{1}, k_{2} ...,k_{n}\}$ чётная, и $«-»$, если нечётная.

Чтобы описать это математически, введём выражение $P\{k_{1}, k_{2} ...,k_{n}\}$, которое будет обозначать число инверсий в соответствующей перестановке. В этом случае удобно определять знак произведения таким образом:

$$(-1)^{P\{k_{1}, k_{2} ...,k_{n}\}}=\begin{cases}
+1 & \text{ в случае чётной перестановки, } \\ 
-1 & \text{ в случае нечётной перестановки. } 
\end{cases}$$

Сумма всех возможных произведений элементов матрицы $A$, описанных вышеуказанным образом, и будет определителем матрицы $A$:

$$detA=\sum_{\{k_{1}, k_{2} ...,k_{n}\}}a_{1k_{1}}a_{2k_{2}}...a_{nk_{n}}(-1)^{P\{k_{1}, k_{2} ...,k_{n}\}}.$$

Это правило также выводится из формулы определения через миноры. С выводом можно ознакомиться в книге В. А. Ильина и Э. Г. Позняка «Линейная алгебра» из списка литературы.

В случае $n=2$ формула элементарно проверяется, если принять во внимание, что существуют всего две перестановки множества $\{1,2\}$: $\{1,2\}$ и $\{2,1\}$, первая из которых считается чётной, вторая — нечётной. Таким образом, получим:

$$\begin{vmatrix}
a_{11} & a_{12}\\ 
a_{21} & a_{22}
\end{vmatrix}=a_{11}a_{22} - a_{12}a_{21}.$$

В NumPy определитель матрицы вычисляется по функции `numpy.linalg.det(a)`, где `a` — матрица.

__Пример__

Найдём определители из примеров выше через Python:

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[1 2 1]
 [1 1 4]
 [2 3 6]]
Определитель:
-1


In [ ]:
b = np.array([[-1, -4, 0, -2], [0, 1, 5, 4], [3, 1, 1, 0], [-1, 0, 2, 2]])
print(f'Матрица:\n{b}')
print(f'Определитель:\n{np.linalg.det(b):.0f}')

Матрица:
[[-1 -4  0 -2]
 [ 0  1  5  4]
 [ 3  1  1  0]
 [-1  0  2  2]]
Определитель:
-12


### Свойства определителей

__1.__ Определитель транспонированной матрицы равен определителю исходной:

$$detA^{T}=detA.$$

__2.__ Умножение строки или столбца матрицы на число $\lambda$ приведёт к умножению определителя матрицы на то же число. 

- Доказательство этого свойства элементарно, так как, исходя из формулы определителя, множитель из указанной строки будет в каждом из слагаемых при нахождении определителя разложением по этой строке/столбцу, что равнозначно его умножению на это число.

__3.__ Перестановка любых двух строк или столбцов матрицы приводит к изменению знака определителя.

- Это происходит из-за того, что дополнительная транспозиция меняет чётность перестановки.

__4.__ Если матрица имеет нулевую строку или столбец, то определитель равен нулю. 

- По аналогии с пунктом 2: в каждом из слагаемых будет множитель — элемент из этой строки (столбца), а значит, все они обнулятся.

__5.__ Если две строки (столбца) матрицы равны между собой, то определитель этой матрицы равен нулю. 

- Согласно свойству 3, перестановка двух строк (столбцов) приводит к смене знака определителя. С другой стороны, если строки равны, то определитель измениться не должен. Оба эти условия одновременно выполняются, только когда определитель равен нулю:

$$detA=-detA \Rightarrow detA=0.$$

__6.__ Если две строки (столбца) матрицы линейно зависимы, то определитель этой матрицы равен нулю.

- Согласно свойству 2, множитель строки (столбца) можно вынести за знак определителя. Вынеся таким образом множитель пропорциональности, мы получим матрицу, имеющую две одинаковых строки (столбца). Согласно свойству 5, определитель такой матрицы равен нулю.

__7.__ Определитель матрицы треугольного вида равен произведению элементов, стоящих на её главной диагонали:

$$\begin{vmatrix}
a_{11} & a_{12} & a_{13} & \cdots & a_{1n}\\ 
0 & a_{22} & a_{23} & \cdots & a_{2n}\\ 
0 & 0 & a_{33} & \cdots & a_{3n}\\ 
\cdots & \cdots & \cdots & \ddots & \cdots\\ 
0 & 0 & 0 & \cdots & a_{nn}
\end{vmatrix}=a_{11}\cdot a_{22}\cdot ... \cdot a_{nn}.$$

__8.__ Если матрица $A$ ортогональна, то определитель такой матрицы:

$$detA = \pm1.$$

__9.__ Для двух квадратных матриц одинакового размера:

$$det(AB)=detA\cdot detB.$$

__10.__ Если элементы строки (столбца) матрицы считаются результатом суммы, то:

$$\begin{vmatrix}
a_{11} & a_{12} & a_{13} & \cdots & a_{1n}\\ 
\cdots & \cdots & \cdots & \cdots & \cdots\\ 
a_{k1}+b_{k1} & a_{k2}+b_{k2} & a_{k3}+b_{k3} & \cdots & a_{kn}+b_{kn}\\ 
\cdots & \cdots & \cdots & \ddots & \cdots\\ 
a_{1n} & a_{2n} & a_{3n} & \cdots & a_{nn}
\end{vmatrix}=
\begin{vmatrix}
a_{11} & a_{12} & a_{13} & \cdots & a_{1n}\\ 
\cdots & \cdots & \cdots & \cdots & \cdots\\ 
a_{k1} & a_{k2} & a_{k3} & \cdots & a_{kn}\\ 
\cdots & \cdots & \cdots & \ddots & \cdots\\ 
a_{1n} & a_{2n} & a_{3n} & \cdots & a_{nn}
\end{vmatrix}+
\begin{vmatrix}
a_{11} & a_{12} & a_{13} & \cdots & a_{1n}\\ 
\cdots & \cdots & \cdots & \cdots & \cdots\\ 
b_{k1} & b_{k2} & b_{k3} & \cdots & b_{kn}\\ 
\cdots & \cdots & \cdots & \ddots & \cdots\\ 
a_{1n} & a_{2n} & a_{3n} & \cdots & a_{nn}
\end{vmatrix}.$$

__11.__ Если к одной из строк матрицы прибавить другую, умноженную на число, её определитель не изменится:

$$\begin{vmatrix}
\cdots & \cdots & \cdots & \cdots & \cdots\\ 
a_{i1} & a_{i2} & a_{i3} & \cdots & a_{in}\\ 
\cdots & \cdots & \cdots & \cdots & \cdots\\ 
a_{k1}& a_{k2}& a_{k3} & \cdots & a_{kn}\\ 
\cdots & \cdots & \cdots & \cdots & \cdots\\ 
\end{vmatrix}=
\begin{vmatrix}
\cdots & \cdots & \cdots & \cdots & \cdots\\ 
a_{i1} & a_{i2} & a_{i3} & \cdots & a_{in}\\ 
\cdots & \cdots & \cdots & \cdots & \cdots\\ 
a_{k1}+\lambda a_{i1} & a_{k2}+\lambda a_{i2}& a_{k3}+\lambda  a_{i3} & \cdots & a_{kn}+\lambda  a_{in}\\ 
\cdots & \cdots & \cdots & \cdots & \cdots\\ 
\end{vmatrix}.$$

- Такой определитель можно будет представить в виде суммы двух, первый из которых будет равен исходному, а второй — содержать линейно зависимые строки, в связи с чем обратится в ноль.

__Пример__

Вычислим определитель:

$$\begin{vmatrix}
2 & -4 & 1\\ 
-3 & 2 & 5\\ 
1 & 2 & 3
\end{vmatrix}.$$

__Решение__

Так как при прибавлении к строке другой строки, умноженной на число, определитель не меняется, мы можем осуществить некоторые преобразования для обнуления максимального количества элементов:

- преобразуем первую строку, вычтя третью, умноженную на 2;
- преобразуем вторую строку, прибавив к ней третью, умноженную на 3.

Получим:

$$\begin{vmatrix}
2 & -4 & 1\\ 
-3 & 2 & 5\\ 
1 & 2 & 3
\end{vmatrix}=
\begin{vmatrix}
0 & -8 & -5\\ 
0 & 8 & 14\\ 
1 & 2 & 3
\end{vmatrix}.$$

Далее поменяем местами первую и третью строки, при этом знак определителя изменится, по свойству 3:

$$-\begin{vmatrix}
1 & 2 & 3\\
0 & 8 & 14\\ 
0 & -8 & -5
\end{vmatrix}.$$

И прибавим к третьей строке вторую:

$$-\begin{vmatrix}
1 & 2 & 3\\
0 & 8 & 14\\ 
0 & 0 & 9
\end{vmatrix}.$$

Мы получили матрицу треугольного вида, определитель которой равен произведению диагональных элементов:

$$-\begin{vmatrix}
1 & 2 & 3\\
0 & 8 & 14\\ 
0 & 0 & 9
\end{vmatrix}=-1\cdot8\cdot9=-72.$$

Проверим через Python:

In [ ]:
a = np.array([[2, -4, 1], [-3, 2, 5], [1, 2, 3]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ 2 -4  1]
 [-3  2  5]
 [ 1  2  3]]
Определитель:
-72


__Определение__

Матрица называется _сингулярной_ или _вырожденной_, если её определитель равен нулю.

## Ранг матрицы

Введём понятие минора $k$-го порядка.

_Минором $k$-го порядка_ матрицы $A$ размера $m\times n$ будем называть определитель $k$-го порядка, где $k$ не превосходит меньшее из $m$ и $n$, с элементами, лежащими на пересечении любых $k$ строк и любых $k$ столбцов матрицы $A$.

__Определение__

Предположим, что хотя бы один из элементов матрицы $A$ отличен от нуля. Тогда найдётся целое положительное число $r$, такое, что:<br>
* у матрицы $A$ есть минор $r$-го порядка, отличный от нуля;<br>
* любой минор порядка $r+1$ и выше равен нулю.

Число $r$, удовлетворяющее этим требованиям, назовём _рангом матрицы $A$_ и обозначим $rankA$, а минор $r$-го порядка — _базисным минором_.

Иными словами, ранг матрицы — это порядок её максимального невырожденного (или базисного) минора.

__Определение__

_Строчным рангом матрицы_ называется максимальное число линейно независимых строк этой матрицы.

_Столбцовым рангом матрицы_ называется максимальное число линейно независимых столбцов этой матрицы.

__Теорема__

_Строчный ранг матрицы всегда совпадает со столбцовым и равен максимальному размеру её невырожденного минора._

При работе с рангом матрицы важно знать, какие преобразования матриц не приводят к изменению их ранга:

- транспонирование;

- перестановка местами двух строк (столбцов);

- умножение всех элементов строки (столбца) на число, не равное нулю;

- прибавление ко всем элементам строки (столбца) соответствующих элементов другой строки (столбца);

- выбрасывание нулевой строки (столбца);

- выбрасывание строки (столбца), служащей линейной комбинацией других строк (столбцов).

__Пример__

Найдём ранг матрицы:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26\\ 
5 & 14 & 22 & 31 & 40
\end{pmatrix}.$$

Четвёртая строка считается суммой второй и третьей строк, а значит, её можно отбросить:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26
\end{pmatrix}.$$

Из второй и третьей строк вычтем первую, умноженную на $2$ и $3$ соответственно:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 2 & 5 & 8 & 11
\end{pmatrix}.$$

И вычтем из третьей строки вторую, умноженную на $2$:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 0 & 1 & 2 & 3
\end{pmatrix}.$$

Таким образом, ранг матрицы равен $3$.

В контексте машинного обучения эта характеристика особенно важна, так как наличие линейно зависимых строк в обучающей выборке приводит к избыточности информации и усложнению модели. Такие строки из обучающих выборок можно удалять без ущерба для точности получаемой модели, осуществляя сжатие данных без потерь.

В NumPy ранг матрицы вычисляется по функции `numpy.linalg.matrix_rank(a)`, где `a` — матрица.

С применением ранга матрицы проверяются векторы на линейную зависимость.

Имея несколько векторов, мы можем составить из них матрицу, где эти векторы окажутся строками или столбцами. Векторы будут линейно независимы только тогда, когда ранг полученной матрицы совпадёт с числом векторов. 

In [ ]:
x = [1, 2, 3]
y = [2, 2, 2]
z = [3, 3, 3]

a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


## Понятие обратной матрицы

Матрица $B$ называется _правой обратной матрицей_ к $A$, если:

$$AB=E,$$

где $E$ — единичная матрица.

Матрица $C$ называется _левой обратной матрицей_ к $A$, если:

$$CA=E.$$

__Утверждение__

Если для матрицы $A$ существуют левая и правая обратные матрицы, то они совпадают между собой.

__Теорема__

Чтобы для матрицы $A$ существовали левая и правая обратные матрицы, определитель матрицы $A$ должен быть отличен от нуля.

Таким образом, в случае невырожденных матриц можно опускать термины «левая» и «правая» и говорить просто о матрице, _обратной по отношению к матрице_ $A$, и обозначать её символом $A^{-1}$:

$$A^{-1}A=AA^{-1}=E,$$

где $E$ — единичная матрица.

Если для матрицы $A$ существует обратная матрица, то она единственна.

_Если матрица вырождена, то у неё нет обратной матрицы._

- __Доказательство__

Допустим, матрица $A$ вырождена, то есть $detA=0$, и для неё существует обратная матрица $A^{-1}$. Тогда из соотношения $A\cdot A^{-1}=E$ получим:

$detA\cdot detA^{-1}=detE=1$, а $detA\neq0$,

что противоречит условию. То есть, если у матрицы есть обратная, значит, матрица не вырождена. Что и требовалось доказать.

__Нахождение обратной матрицы (метод присоединённой матрицы)__

Для ввода алгоритма нахождения обратной матрицы к матрице $A$ введём понятие алгебраического дополнения.

_Алгебраическим дополнением_ элемента $a_{ij}$ квадратной матрицы $A$ порядка $n$ называется минор $M_{ij}$, умноженный на $(-1)^{i+j}$, и обозначается $A_{ij}$:

$$A_{ij}=(-1)^{i+j}M_{ij}.$$

Алгоритм нахождения обратной матрицы следующий:

1. Найти определитель матрицы $A$ и убедиться, что $detA\neq0$.

2. Составить алгебраические дополнения $A_{ij}$ для каждого элемента матрицы $A$ и записать матрицу $A^{*}=(A_{ij})$ из найденных алгебраических дополнений.

3. Записать обратную матрицу, определённую по формуле:

$$A^{-1}=\frac{1}{detA}\cdot A^{*T}.$$

Матрицу $A^{*T}$ часто называют _присоединённой (союзной)_ к матрице $A$.

__Пример__

Найдём обратную матрицу для матрицы:

$$A = \begin{pmatrix}
1 & 2 & 1\\ 
1 & 1 & 4\\ 
2 & 3 & 6
\end{pmatrix}.$$

__Решение__

1. Найдём определитель:

$$\begin{vmatrix}
1 & 2 & 1\\ 
1 & 1 & 4\\ 
2 & 3 & 6
\end{vmatrix} = -6 + 4 + 1 = -1. $$

2. Найдём алгебраические дополнения для каждого элемента:

$$A_{11}=(-1)^{2}\begin{vmatrix}
1 & 4\\ 
3 & 6
\end{vmatrix} = -6,~
A_{12}=(-1)^{3}\begin{vmatrix}
1 & 4\\ 
2 & 6
\end{vmatrix} = 2,~
A_{13}=(-1)^{4}\begin{vmatrix}
1 & 1\\ 
2 & 3
\end{vmatrix} = 1,$$
$$A_{21}=(-1)^{3}\begin{vmatrix}
2 & 1\\ 
3 & 6
\end{vmatrix} = -9,~
A_{22}=(-1)^{4}\begin{vmatrix}
1 & 1\\ 
2 & 6
\end{vmatrix} = 4,~
A_{23}=(-1)^{5}\begin{vmatrix}
1 & 2\\ 
2 & 3
\end{vmatrix} = 1,$$
$$A_{31}=(-1)^{4}\begin{vmatrix}
2 & 1\\ 
1 & 4\\ 
\end{vmatrix} = 7,~
A_{32}=(-1)^{5}\begin{vmatrix}
1 & 1\\ 
1 & 4
\end{vmatrix} = -3,~
A_{33}=(-1)^{6}\begin{vmatrix}
1 & 2\\ 
1 & 1\\ 
\end{vmatrix} = -1.$$

Полученная матрица из алгебраических дополнений:

$$A^{*} = \begin{pmatrix}
-6 & 2 & 1\\ 
-9 & 4 & 1\\ 
7 & -3 & -1
\end{pmatrix},~
A^{*T} = \begin{pmatrix}
-6 & -9 & 7\\ 
2 & 4 & -3\\ 
1 & 1 & -1
\end{pmatrix}.$$

3. Используя формулу из алгоритма, получим:

$$A^{-1} = \frac{1}{(-1)}\cdot \begin{pmatrix}
-6 & -9 & 7\\ 
2 & 4 & -3\\ 
1 & 1 & -1
\end{pmatrix} = \begin{pmatrix}
6 & 9 & -7\\ 
-2 & -4 & 3\\ 
-1 & -1 & 1
\end{pmatrix}.$$

В NumPy обратные матрицы вычисляются по функции `numpy.linalg.inv(a)`, где `a` — матрица.

In [ ]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=float)
b = np.linalg.inv(a)

print(f'Матрица A:\n{a}\n')
print(f'Матрица B, обратная к A:\n{b}\n')
print(f'Матрица AB (должна быть единичной):\n{a.dot(b)}')

Матрица A:
[[1. 2. 1.]
 [1. 1. 4.]
 [2. 3. 6.]]

Матрица B, обратная к A:
[[ 6.  9. -7.]
 [-2. -4.  3.]
 [-1. -1.  1.]]

Матрица AB (должна быть единичной):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Практическое задание

Все задания рекомендуется выполнять вручную, проверяя полученные результаты с использованием NumPy.

__1.__ Вычислите определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


__2.__ Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__3.__  Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__4.__ Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

## Литература

1. Ильин В. А., Позняк Э. Г. Линейная алгебра: Учеб. для вузов. — 6-е изд. — М.: Физматлит, 2005.
2. Форсайт Дж., Молер К. Численное решение систем линейных алгебраических уравнений. — М.: Мир, 1969.
3. Кострикин А. И., Манин Ю. И. Линейная алгебра и геометрия. Учеб. пособие для вузов. — 2-е изд. — М.: Наука, Главная редакция физико-математической литературы, 1986.

## Дополнительные материалы

1. [Способы задать матрицу в NumPy](https://docs.scipy.org/doc/numpy-1.10.1/user/basics.creation.html).
2. [numpy.transpose](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.transpose.html).
3. [array.T](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ndarray.T.html).
4. [Перемножение матриц в NumPy](https://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html#matrix-and-vector-products).
5. [Определитель матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.det.html)

6. [Ранг матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.matrix_rank.html)

7. [Обращение матриц в NumPy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)